### ISSUE TITLE
求php版本

### ISSUE THREAD

**Issue by dreamsleet** [btbxbob/wxpay-decrypt-refund-notify#1]
@btbxbob 如题，希望大神有空能搞一份**PHP**版本的出来造福我等不懂go语言的菜鸟！感谢！2271765919@qq.com

**Comment by wensonsmith** [comment]
@dreamsleet  刚好找到一个： https://github.com/lampnick/wxpay-refund-notify-decrypt-helper/blob/master/WxpayRefundNotifyHelper.php

**Comment by dreamsleet** [comment]
非常感谢您的热心帮助，谢谢！

**Comment by wensonsmith** [comment]
微信支付官方 hin 不给力，文档写的不清不楚，给的这个 demo 是 Go 语言的。 刚才那个 php 版本的貌似有问题，我还是解密不出来 😞

**Comment by dreamsleet** [comment]
,嗯，我稍微看了下那个aes256 pk7加解密什么，发现里面涉及到不少的参数，官方写的文档太不具体了。我发邮件给他们他们回给我推荐你这个GO语言的。这又不是什么不能让人知道的。我就费解了，以他们的本事 ，直接给份php的解密方法不好吗？这么为难我这种不懂加密和算法的菜鸟好吗




------------------ 原始邮件 ------------------
发件人: "Wenson Smith";<notifications@github.com>;
发送时间: 2017年8月11日(星期五) 下午2:28
收件人: "btbxbob/wxpay-decrypt-refund-notify"<wxpay-decrypt-refund-notify@noreply.github.com>; 
抄送: ""<67085399@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [btbxbob/wxpay-decrypt-refund-notify] 求php版本 (#1)




微信支付官方 hin 不给力，文档写的不清不楚，给的这个 demo 是 Go 语言的。 刚才那个 php 版本的貌似有问题，我还是解密不出来 😞

**Comment by dreamsleet** [comment]
我刚才测试了，上面那个php版本没问题，可以解密出来

**Comment by btbxbob** [comment]
我算是官方的，写这个demo是因为golang没有aes ecb。
刚才我确认了一次文档，按照文档的步骤没问题的。
php版本的我看了一下就是封装有点问题，把base64_decode放在了handle()里。其他的和我的方法一样的。

**Comment by btbxbob** [comment]
// 1. decode Base64
	deBase64, err := base64.StdEncoding.DecodeString(crypted)
	// 2. md5 original trading key
	hasher := md5.New()
	hasher.Write([]byte(key))
	result := hex.EncodeToString(hasher.Sum(nil))
	//3. aes ecb decrypt
	block, err := aes.NewCipher([]byte(result))
	if err != nil {
		panic(err.Error())
	}
	mode := NewECBDecrypter(block)
	content := []byte(deBase64)
	mode.CryptBlocks(content, content)

不管哪个语言，严格按照这里的1,2,3即可，php也一样。

**Comment by btbxbob** [comment]
https://github.com/btbxbob/wxpay-refund-notify-decrypt-helper

我在上面的原版基础上，重新调整了一下结构，增加了注释。
但是我目前还没有全面测试，如果有任何人测试之后我再向原作者发起PR.

**Comment by wensonsmith** [comment]
非常感谢 ！ @btbxbob 

但是现在有一个问题是 `mcrypt_create_iv` 这个函数在 PHP 7.1 中已经 `deprecated` , 
我按照你代码里的思路，用 `openssl_decrypt` 这个函数取解密，没搞出来。。。

大神能指导一下怎么用 `openssl` 解密么？ 多谢

**Comment by btbxbob** [comment]
@wensonsmith 后续我更新到https://github.com/btbxbob/wxpay-refund-notify-decrypt-helper里

**Comment by btbxbob** [comment]
@wensonsmith 已经更新到  https://github.com/btbxbob/wxpay-refund-notify-decrypt-helper 里。
